sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - release/2.5-RC

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
#    - php: 7.3
#      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      curl -LO https://phar.phpunit.de/phpunit-7.phar
      chmod +x phpunit-7.phar
      which phpunit
      phpunit --version
      sudo mv phpunit-7.phar /usr/local/bin/phpunit
      which phpunit
      phpunit --version
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer install
      /usr/local/bin/phpunit --version
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      composer global require phpcompatibility/php-compatibility
      composer global require phpcompatibility/phpcompatibility-paragonie
      composer global require phpcompatibility/phpcompatibility-wp
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/php-compatibility,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-paragonie,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-wp
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      ls -la
      /usr/local/bin/phpunit --version
      /usr/local/bin/phpunit
      WP_MULTISITE=1 /usr/local/bin/phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
