sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - unit-testing

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=5.7
#    - php: 7.3
#      env: WP_VERSION=5.7.1
#    - php: 7.2
#      env: WP_VERSION=5.7.1
#    - php: 7.1
#      env: WP_VERSION=5.7.1
#    - php: 7.0
#      env: WP_VERSION=5.7.1


before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      wget https://phar.phpunit.de/phpunit-7.5.9.phar
      chmod +x phpunit-7.5.9.phar
      sudo mv phpunit-7.5.9.phar /usr/local/bin/phpunit
      which phpunit
      ./vendor/bin/phpunit --version
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=7.*"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require wp-coding-standards/wpcs
      composer global require phpcompatibility/php-compatibility
      composer global require phpcompatibility/phpcompatibility-paragonie
      composer global require phpcompatibility/phpcompatibility-wp
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/phpcompatibility/php-compatibility,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-paragonie,$HOME/.composer/vendor/phpcompatibility/phpcompatibility-wp
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      ./vendor/bin/phpunit
      WP_MULTISITE=1 ./vendor/bin/phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      phpcs
    fi
